import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/styles/global/css";

const notoSansKR = Noto_Sans_KR({
  weight: ["400", "700"],
  variable: "--font-noto-sans-kr",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKR}`}
      >
        {children}
      </body>
    </html>
  );
}
